name: Update GitHub Pages

on:
  push:
    tags:

jobs:
  pages:
    name: Update GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code from release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          path: release
      - name: Checkout and push to gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: pages
          ref: gh-pages
          run: |
            cp ../release/README.md ./docs/index.md
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "docs: update docs for ${{ github.ref_name }}"
            git push
